// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/zine-ios/ZineiOS.tsx": () => import("../components/mockups/zine-ios/ZineiOS.tsx"),
  "./components/mockups/zine-web/Desktop.tsx": () => import("../components/mockups/zine-web/Desktop.tsx"),
  "./components/mockups/zine-web/Mobile.tsx": () => import("../components/mockups/zine-web/Mobile.tsx")
};
